"""Tier-0 cold-start prerequisites — the toolchain + a venv-compatible Python.

Runs under the *system* python3, BEFORE any Bob venv exists (the shell stub `install_prereqs.sh`/`.bat`
ensures python3, then `exec python3 -m bob.kernel prereqs`). The per-manager package +
python-provisioning logic lives behind the osenv seams (PACKAGE_MAP / resolve_package_name /
install_package / bob_python / linux_cmake3 / the CUDA cluster). Stdlib + osenv only — nothing here may
import a venv-only dependency.

  python3 -m bob.kernel prereqs          # GPU build (installs the CUDA toolkit when an NVIDIA GPU is present)
  python3 -m bob.kernel prereqs --cpu    # CPU-only tier (skips the CUDA toolkit)
"""
import shutil
import subprocess
import sys
from pathlib import Path

_SCRIPTS = Path(__file__).resolve().parent.parent
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

import osenv  # noqa: E402

REPO = osenv.REPO


def _have(name: str) -> bool:
    return shutil.which(name) is not None


def _sudo() -> list:
    """['sudo'] when it's present and we're not already root, else [] — so the same install path works on
    a normal desktop (sudo) AND a root container/minimal image where sudo isn't installed (CI distros)."""
    import os
    if hasattr(os, "geteuid") and os.geteuid() == 0:
        return []
    return ["sudo"] if shutil.which("sudo") else []


def _winget(package: str, extra=()):  # pragma: no cover — Windows path
    """Install a winget package, tolerating the already-installed exit code. Port of Install-WithWinget."""
    argv = ["winget", "install", package, *extra, "--accept-package-agreements",
            "--accept-source-agreements", "--disable-interactivity"]
    rc = subprocess.run(argv).returncode
    if rc not in (0, -1978335189):
        raise RuntimeError(f"winget install {package} failed (exit {rc})")


# --- Linux ----------------------------------------------------------------------------------------

def _set_linux_cuda_path(root: str, host_cxx: str = None) -> None:
    """Wire a CUDA toolkit root onto the invoking user's shell PATH (+ NVCC_CCBIN). fish gets a conf.d
    drop-in (no sudo); bash/zsh get /etc/profile.d/cuda.sh when missing."""
    import tempfile
    if _have("fish"):
        confd = osenv.home_config_dir("fish") / "conf.d"
        try:
            confd.mkdir(parents=True, exist_ok=True)
            lines = ["# Bob — CUDA toolkit on PATH for fish. Regenerated by install_prereqs.",
                     f"set -gx CUDA_PATH {root}", f"fish_add_path {root}/bin"]
            if host_cxx:
                lines.append(f"set -gx NVCC_CCBIN {host_cxx}")
            (confd / "bob-cuda.fish").write_text("\n".join(lines) + "\n", encoding="utf-8")
            print(f"  wired CUDA onto fish PATH -> {confd / 'bob-cuda.fish'} (open a new shell to pick it up)",
                  file=sys.stderr)
        except OSError as e:
            print(f"  couldn't write the fish CUDA drop-in: {e} (add {root}/bin to fish PATH manually)",
                  file=sys.stderr)

    if not Path("/etc/profile.d/cuda.sh").exists():
        sh = ["# Bob — CUDA toolkit on PATH (bash/zsh login shells).",
              f"export CUDA_PATH={root}", f'export PATH="{root}/bin:$PATH"']
        if host_cxx:
            sh.append(f"export NVCC_CCBIN={host_cxx}")
        try:
            tmp = Path(tempfile.gettempdir()) / "bob-cuda.sh"
            tmp.write_text("\n".join(sh) + "\n", encoding="utf-8")
            subprocess.run([*_sudo(), "cp", str(tmp), "/etc/profile.d/cuda.sh"], check=False)
            subprocess.run([*_sudo(), "chmod", "0644", "/etc/profile.d/cuda.sh"], check=False)
            tmp.unlink(missing_ok=True)
            if Path("/etc/profile.d/cuda.sh").exists():
                print("  wired CUDA onto bash/zsh PATH -> /etc/profile.d/cuda.sh", file=sys.stderr)
        except OSError as e:
            print(f"  couldn't write /etc/profile.d/cuda.sh: {e} (add {root}/bin to PATH manually)",
                  file=sys.stderr)


def ensure_cuda_toolkit(cpu: bool = False):
    """Tier-0 CUDA-toolkit seam, shared by install_prereqs AND `bob update` so an update ensures the same
    prerequisite a fresh setup does. Returns a toolkit root >= the GPU's floor, or None when none is
    available (a CPU build, or a GPU box with no reachable toolkit — e.g. an atomic host with read-only
    /usr). On a mutable Linux distro it installs the toolkit via the package seam when absent, then
    re-probes. Never raises: callers decide what to do with None — setup and update fall back to a CPU
    build, matching each other; osenv.cuda_missing_message() is the shared guidance for that case."""
    if cpu:
        return None
    arch = (osenv.gpu_arch() or {}).get("CudaArch", 120)
    root = osenv.best_cuda_root(arch)
    if root:
        return root
    if osenv.os_name() == "linux" and not osenv.is_atomic_linux():
        mgr = osenv.linux_package_manager()
        if mgr:
            pkg = osenv.resolve_package_name("cuda", mgr)
            print(f"  install {pkg} (CUDA toolkit) ...", file=sys.stderr)
            try:
                osenv.install_package(pkg)
            except (RuntimeError, KeyError) as e:
                print(f"  {pkg} failed: {e}", file=sys.stderr)
            root = osenv.best_cuda_root(arch)
    return root


def _install_linux_cuda(manager: str) -> None:
    """Install the CUDA toolkit (if absent) + wire it onto PATH. The build discovers the toolkit by
    probing disk, so PATH is a convenience. Blackwell (sm_120) needs >= 12.8. Port of Install-LinuxCuda."""
    root = ensure_cuda_toolkit(cpu=False)
    if not root:
        print(f"  {osenv.cuda_missing_message()}", file=sys.stderr)
        return
    host_cxx = osenv.cuda_host_compiler()
    print(f"  CUDA toolkit : {root}", file=sys.stderr)
    if host_cxx:
        print(f"  nvcc host g++: {host_cxx} (the default g++ is too new for nvcc)", file=sys.stderr)
    _set_linux_cuda_path(root, host_cxx)


_ATOMIC_NOTE = """Toolchain layered via rpm-ostree. On an atomic/ostree host (Bazzite / Silverblue /
Kinoite) layered packages apply on the NEXT BOOT — so reboot, then run setup:
    systemctl reboot
    ./setup.sh{cpu}

RECOMMENDED ALTERNATIVE (no reboot, better isolation, simple GPU) — run Bob in a Fedora distrobox:
    distrobox create --name bob --image fedora:latest{nvidia}
    distrobox enter bob
    cd {repo} && ./install_prereqs.sh{cpu} && ./setup.sh{cpu}
Inside the box it's plain Fedora (dnf) — the native build and CUDA passthrough just work, and nothing
touches the immutable host."""


def _layer_atomic(pkgs: list, mgr: str, cpu: bool, from_source: bool = False) -> int:
    """Layer the toolchain on an rpm-ostree host in one transaction. CUDA is intentionally NOT layered on
    the host (it needs NVIDIA's repo + akmods and is fragile on atomic). On the DEFAULT (prebuilt) path the
    driver-only engine runs on the host as-is, so no distrobox is needed; the distrobox note is printed only
    for a --from-source GPU build, where a Fedora distrobox is the blessed Bazzite/Silverblue path."""
    print(f"  layering {len(pkgs)} package(s) via rpm-ostree: {' '.join(pkgs)}", file=sys.stderr)
    try:
        osenv.install_packages(pkgs, manager=mgr)
    except (RuntimeError, KeyError) as e:
        raise RuntimeError(
            f"rpm-ostree layering failed: {e}\nOn an atomic host the recommended path is a Fedora "
            "distrobox instead:\n    distrobox create --name bob --image fedora:latest --nvidia && "
            "distrobox enter bob\nthen run ./install_prereqs.sh + ./setup.sh inside it.")
    if from_source and not cpu:
        print("\n" + _ATOMIC_NOTE.format(cpu="", nvidia=" --nvidia", repo=REPO), file=sys.stderr)
    else:
        print("\n  Atomic host: the driver-only prebuilt engine runs on the host as-is (no distrobox needed). "
              "The toolchain layer applies on the NEXT BOOT — reboot, then run ./setup.sh.", file=sys.stderr)
    return 0


def _prime_sudo(mgr: str, pkgs: list, cpu: bool) -> None:
    """Ask for the sudo password ONCE, up front, and cache it — so the batched install below doesn't
    prompt per package, and a wrong password fails fast (not after hammering every install). No-op when
    already root or sudo is absent (root containers). On failure, raise with the exact manual command +
    the fact that `setup` itself needs NO root — so a user whose sudo is finicky (e.g. fingerprint/polkit
    on a desktop) can install the toolchain by hand and skip straight to the build."""
    if not _sudo():
        return
    print("  sudo is needed to install system packages — you'll be asked for your password once.",
          file=sys.stderr)
    if subprocess.run(["sudo", "-v"]).returncode == 0:
        return
    spec = osenv._linux_pkg_spec(mgr, pkgs)
    manual = (("sudo " if spec["Sudo"] else "") + spec["Exe"] + " " + " ".join(spec["Args"])).strip()
    suffix = " --cpu" if cpu else ""
    raise RuntimeError(
        "sudo authentication failed (sudo rejected the password — this is your system's auth, not Bob).\n"
        "  • Check it's really your sudo password:  sudo -v   (if that also fails, it's a system/config\n"
        "    thing — on a desktop you may normally auth by fingerprint/polkit, not a typed password).\n"
        "  • OR skip sudo entirely — `setup` needs NO root. Install the toolchain by hand, then run setup:\n"
        f"        {manual}\n"
        f"        ./setup.sh{suffix}\n"
        "  • OR configure passwordless sudo, then re-run ./install_prereqs.sh.")


def _install_linux(cpu: bool, from_source: bool = False) -> int:
    """Port of Install-LinuxPrereqs: toolchain via PACKAGE_MAP (ONE batched install = one sudo prompt), a
    venv-compatible Python, a build-usable cmake 3.x, optional CUDA + cron + docker. On an atomic/ostree
    host (rpm-ostree) the toolchain LAYERS and applies on the next boot. Fails non-zero if the toolchain
    install fails.

    The multi-GB CUDA Toolkit is installed ONLY with from_source=True: the default install uses the
    driver-only prebuilt engine (CUDA runtime libs bundled), so it needs the NVIDIA driver but never nvcc."""
    mgr = osenv.linux_package_manager()
    if not mgr:
        raise RuntimeError("No supported package manager (apt/dnf/pacman/zypper/rpm-ostree) found. "
                           "Install the toolchain manually — see docs/MANUAL-INSTALL.md.")
    atomic = (mgr == "rpm-ostree")
    print(f"=== Linux prerequisites ({mgr}{' — atomic/ostree host' if atomic else ''}) ===", file=sys.stderr)

    toolchain = ["git", "curl", "toolchain-cc", "make", "cmake", "ninja", "go", "node", "npm",
                 "python", "python-pip", "python-venv"]
    pkgs = []
    for logical in toolchain:
        name = osenv.resolve_package_name(logical, mgr)
        if name and name not in pkgs:
            pkgs.append(name)  # None => bundled on this manager, skip

    _prime_sudo(mgr, pkgs, cpu)

    if atomic:
        return _layer_atomic(pkgs, mgr, cpu, from_source)

    print(f"  installing {len(pkgs)} package(s): {' '.join(pkgs)}", file=sys.stderr)
    try:
        osenv.install_packages(pkgs, manager=mgr)
    except (RuntimeError, KeyError) as e:
        raise RuntimeError(f"toolchain install failed: {e}\n"
                           f"Fix the error above, then re-run ./install_prereqs.sh{' --cpu' if cpu else ''}.")

    # Guarantee a venv-compatible Python 3.11/3.12 (uv-provisioned if the system one is out of range).
    try:
        py = osenv.bob_python()
        if py:
            print(f"  python (venv) ready: {py}", file=sys.stderr)
        else:
            print("  no venv-compatible Python (3.11/3.12) found and couldn't provision one via uv — "
                  "install Python 3.12 and re-run.", file=sys.stderr)
    except (OSError, subprocess.SubprocessError) as e:
        print(f"  python provisioning failed: {e} (bootstrap will retry)", file=sys.stderr)

    # llama.cpp/whisper.cpp reject cmake >= 4.0; the distro cmake is 4.x on rolling distros. Cache a 3.x.
    try:
        cm3 = osenv.linux_cmake3(REPO)
        print(f"  cmake 3.x ready: {cm3}", file=sys.stderr)
    except (RuntimeError, OSError) as e:
        print(f"  couldn't provision cmake 3.x: {e} (setup will retry)", file=sys.stderr)

    if cpu:
        print("  --cpu: skipping CUDA toolkit (CPU-only tier).", file=sys.stderr)
    elif not from_source:
        # Prebuilt engines bundle the CUDA runtime libs (driver-only), so a default install does NOT pull the
        # multi-GB CUDA Toolkit. nvcc is needed only for a --from-source GPU build (ensure_engine self-heals
        # the toolkit then on a mutable distro, or ./install_prereqs.sh --from-source installs it up front).
        if _have("nvidia-smi"):
            print("  NVIDIA GPU present — the driver-only prebuilt engine needs no CUDA Toolkit. For a source "
                  "GPU build instead, re-run with --from-source.", file=sys.stderr)
        else:
            print("  No NVIDIA GPU (nvidia-smi absent) — CPU tier.", file=sys.stderr)
    elif _have("nvidia-smi"):
        _install_linux_cuda(mgr)
    else:
        print("  No NVIDIA GPU (nvidia-smi absent) — CPU tier. Skipping CUDA.", file=sys.stderr)

    # cron scheduler — Linux parity for Windows Scheduled Tasks (backs `bob agent install`). Optional.
    cron_pkg = osenv.resolve_package_name("cron", mgr)
    if _have("crontab"):
        print("  cron ok (crontab present)", file=sys.stderr)
    else:
        print(f"  install {cron_pkg} (cron scheduler for 'bob agent install') ...", file=sys.stderr)
        try:
            osenv.install_package(cron_pkg)
        except (RuntimeError, KeyError) as e:
            print(f"  {cron_pkg} failed: {e} (optional — needed only for scheduled agents)", file=sys.stderr)
    if _have("crontab") and _have("systemctl"):
        for svc in dict.fromkeys([cron_pkg, "cronie", "crond", "cron"]):
            if subprocess.run([*_sudo(), "systemctl", "enable", "--now", svc],
                              capture_output=True).returncode == 0:
                break

    if _have("docker"):
        print("  docker ok", file=sys.stderr)
    else:
        print("  docker not found (optional — needed only for the compose services). Install docker + "
              "add your user to the docker group.", file=sys.stderr)

    # The toolchain install above raises on failure (batched), so reaching here means it succeeded.
    print(f"\nLinux prerequisites done. Run: ./setup.sh{' --cpu' if cpu else ''}", file=sys.stderr)
    return 0


# --- Windows -------------------------------------------------------------------------------------

_VSWHERE = r"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"


def _install_windows(cpu: bool, from_source: bool = False) -> int:  # pragma: no cover — Windows only (+ CI acceptance)
    """Windows path: VS2022 C++, Node+uv, Go+Python312 (scoop/winget),
    CUDA (GPU-aware, only with --from-source), cmake 3.x, Docker Desktop."""
    if not _have("git"):
        raise RuntimeError("git not found. Install Git from https://git-scm.com, then re-run install_prereqs.bat.")
    have_scoop = _have("scoop")
    print(f"  git ok; scoop {'ok' if have_scoop else 'absent (using winget for go/python)'}", file=sys.stderr)

    # VS2022 with the Desktop C++ workload.
    vs_install = ""
    if Path(_VSWHERE).exists():
        vs_install = subprocess.run([_VSWHERE, "-latest", "-products", "*", "-requires",
                                     "Microsoft.VisualStudio.Workload.NativeDesktop", "-property",
                                     "installationPath"], capture_output=True, text=True).stdout.strip()
    if vs_install:
        print("  VS2022 ok", file=sys.stderr)
    else:
        raise RuntimeError("VS2022 'Desktop development with C++' workload not found — required to compile "
                           "llama.cpp. Install VS2022 (winget install Microsoft.VisualStudio.2022.Community), "
                           "add the 'Desktop development with C++' workload, then re-run install_prereqs.bat.")

    # Node.js + uv.
    if _have("node"):
        print("  node ok", file=sys.stderr)
    else:
        _winget("OpenJS.NodeJS")
    if _have("uvx"):
        print("  uv ok", file=sys.stderr)
    else:
        _winget("astral-sh.uv")

    # Go + Python 3.12.
    if _have("go"):
        print("  go ok", file=sys.stderr)
    elif have_scoop:
        subprocess.run(["scoop", "install", "go"])
    else:
        _winget("GoLang.Go")
    py_ok = _have("python") and osenv.python_at_least("python", "3.12") and \
        (subprocess.run(["python", "--version"], capture_output=True, text=True).stdout.find("3.12") >= 0)
    if py_ok:
        print("  python 3.12 ok", file=sys.stderr)
    elif have_scoop:
        has_py = subprocess.run(["scoop", "prefix", "python312"], capture_output=True).returncode == 0
        if has_py:
            print("  python312 ok", file=sys.stderr)
        else:
            subprocess.run(["scoop", "install", "python312"])
    else:
        _winget("Python.Python.3.12")

    # CUDA (GPU-aware). Installed only for a --from-source GPU build; the default install uses the driver-only
    # prebuilt engine (CUDA runtime libs bundled), so nvcc is not needed.
    if cpu:
        print("  --cpu: skipping CUDA toolkit (CPU-only tier).", file=sys.stderr)
    elif not from_source:
        print("  Prebuilt engine is driver-only — skipping the CUDA Toolkit. For a source GPU build, re-run "
              "with --from-source.", file=sys.stderr)
    else:
        gpu = osenv.gpu_arch()
        arch = gpu["CudaArch"] if gpu else 120
        root = osenv.best_cuda_root(arch)
        if gpu:
            print(f"  Detected GPU: {gpu['Gen']} (sm_{gpu['CudaArch']})", file=sys.stderr)
        if root:
            print(f"  CUDA ok: {root}", file=sys.stderr)
        elif _have("winget"):
            print("  Installing CUDA Toolkit 12.8 (large download)...", file=sys.stderr)
            _winget("Nvidia.CUDA", ["--version", "12.8"])
        else:
            print("  winget not found — install CUDA Toolkit 12.8 manually, then re-run.", file=sys.stderr)

    # cmake 3.x (cmake 4.x excluded by llama.cpp).
    cmake_ok = False
    if _have("cmake"):
        out = subprocess.run(["cmake", "--version"], capture_output=True, text=True).stdout
        import re
        m = re.search(r"(\d+)\.(\d+)\.(\d+)", out)
        if m and (int(m.group(1)), int(m.group(2))) < (4, 0):
            cmake_ok = True
            print(f"  cmake ok ({m.group(0)})", file=sys.stderr)
    if not cmake_ok and Path(_VSWHERE).exists():
        vs_i = subprocess.run([_VSWHERE, "-latest", "-products", "*", "-requires",
                               "Microsoft.VisualStudio.Component.VC.CMake.Project", "-property",
                               "installationPath"], capture_output=True, text=True).stdout.strip()
        bundled = Path(vs_i) / "Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin/cmake.exe"
        if vs_i and bundled.exists():
            cmake_ok = True
            print("  cmake ok (VS bundled 3.31.x)", file=sys.stderr)
    if not cmake_ok:
        print("  Installing cmake 3.31.7 via winget...", file=sys.stderr)
        _winget("Kitware.CMake", ["--version", "3.31.7"])

    # Docker Desktop (optional — only bob up -WithServices needs it; CPU tier skips it).
    docker_exe = Path(r"C:\Program Files\Docker\Docker\Docker Desktop.exe")
    already = cpu or _have("docker") or docker_exe.exists()
    if cpu:
        print("  --cpu: skipping Docker Desktop.", file=sys.stderr)
    elif already:
        print("  Docker Desktop ok", file=sys.stderr)
    else:
        print("  Installing Docker Desktop...", file=sys.stderr)
        _winget("Docker.DockerDesktop")

    if already:
        print("\nAll prerequisites verified. Run setup.bat to build and configure the stack.", file=sys.stderr)
    else:
        print("\nDocker Desktop installed. ACTION REQUIRED: log out of Windows and back in, then run "
              "setup.bat (Docker adds your user to the docker-users group; that takes effect at login).",
              file=sys.stderr)
    return 0


def install_prereqs(cpu: bool = False, from_source: bool = False) -> int:
    """Install all Bob prerequisites (toolchain + a venv-compatible Python). Dispatches Linux vs Windows.
    from_source additionally installs the CUDA Toolkit for a source GPU build; the default is driver-only
    (the prebuilt engine bundles the runtime libs). Returns 0 on success; raises on a fatal toolchain failure."""
    if osenv.os_name() == "windows":
        return _install_windows(cpu, from_source)
    return _install_linux(cpu, from_source)


def main(argv=None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    cpu = "--cpu" in argv or "-Cpu" in argv
    from_source = "--from-source" in argv or "-FromSource" in argv
    try:
        return install_prereqs(cpu=cpu, from_source=from_source)
    except RuntimeError as e:
        print(str(e), file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
