"""Tier-0 cold-start prerequisites (ONE-D Slice D8, DD5) — the toolchain + a venv-compatible Python.

Runs under the *system* python3, BEFORE any Bob venv exists (the shell stub `install_prereqs.sh`/`.bat`
ensures python3, then `exec python3 -m bob.kernel prereqs`). Ports `scripts/install-prereqs.ps1` +
`_common.ps1 Install-WithWinget`; the per-manager package + python-provisioning logic lives behind the
osenv seams (PACKAGE_MAP / resolve_package_name / install_package / bob_python / linux_cmake3 / the CUDA
cluster). Stdlib + osenv only — nothing here may import a venv-only dependency.

  python3 -m bob.kernel prereqs          # GPU build (installs the CUDA toolkit when an NVIDIA GPU is present)
  python3 -m bob.kernel prereqs --cpu    # CPU-only tier (skips the CUDA toolkit)
"""
import shutil
import subprocess
import sys
from pathlib import Path

_SCRIPTS = Path(__file__).resolve().parent.parent
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

import osenv  # noqa: E402

REPO = osenv.REPO


def _have(name: str) -> bool:
    return shutil.which(name) is not None


def _sudo() -> list:
    """['sudo'] when it's present and we're not already root, else [] — so the same install path works on
    a normal desktop (sudo) AND a root container/minimal image where sudo isn't installed (CI distros)."""
    import os
    if hasattr(os, "geteuid") and os.geteuid() == 0:
        return []
    return ["sudo"] if shutil.which("sudo") else []


def _winget(package: str, extra=()):  # pragma: no cover — Windows path
    """Install a winget package, tolerating the already-installed exit code. Port of Install-WithWinget."""
    argv = ["winget", "install", package, *extra, "--accept-package-agreements",
            "--accept-source-agreements", "--disable-interactivity"]
    rc = subprocess.run(argv).returncode
    if rc not in (0, -1978335189):
        raise RuntimeError(f"winget install {package} failed (exit {rc})")


# --- Linux (NC2/NC3) ------------------------------------------------------------------------------

def _set_linux_cuda_path(root: str, host_cxx: str = None) -> None:
    """Wire a CUDA toolkit root onto the invoking user's shell PATH (+ NVCC_CCBIN). fish gets a conf.d
    drop-in (no sudo); bash/zsh get /etc/profile.d/cuda.sh when missing. Port of Set-LinuxCudaPath."""
    import tempfile
    if _have("fish"):
        confd = osenv.home_config_dir("fish") / "conf.d"
        try:
            confd.mkdir(parents=True, exist_ok=True)
            lines = ["# Bob (NC3) — CUDA toolkit on PATH for fish. Regenerated by install_prereqs.",
                     f"set -gx CUDA_PATH {root}", f"fish_add_path {root}/bin"]
            if host_cxx:
                lines.append(f"set -gx NVCC_CCBIN {host_cxx}")
            (confd / "bob-cuda.fish").write_text("\n".join(lines) + "\n", encoding="utf-8")
            print(f"  wired CUDA onto fish PATH -> {confd / 'bob-cuda.fish'} (open a new shell to pick it up)",
                  file=sys.stderr)
        except OSError as e:
            print(f"  couldn't write the fish CUDA drop-in: {e} (add {root}/bin to fish PATH manually)",
                  file=sys.stderr)

    if not Path("/etc/profile.d/cuda.sh").exists():
        sh = ["# Bob (NC3) — CUDA toolkit on PATH (bash/zsh login shells).",
              f"export CUDA_PATH={root}", f'export PATH="{root}/bin:$PATH"']
        if host_cxx:
            sh.append(f"export NVCC_CCBIN={host_cxx}")
        try:
            tmp = Path(tempfile.gettempdir()) / "bob-cuda.sh"
            tmp.write_text("\n".join(sh) + "\n", encoding="utf-8")
            subprocess.run([*_sudo(), "cp", str(tmp), "/etc/profile.d/cuda.sh"], check=False)
            subprocess.run([*_sudo(), "chmod", "0644", "/etc/profile.d/cuda.sh"], check=False)
            tmp.unlink(missing_ok=True)
            if Path("/etc/profile.d/cuda.sh").exists():
                print("  wired CUDA onto bash/zsh PATH -> /etc/profile.d/cuda.sh", file=sys.stderr)
        except OSError as e:
            print(f"  couldn't write /etc/profile.d/cuda.sh: {e} (add {root}/bin to PATH manually)",
                  file=sys.stderr)


def _install_linux_cuda(manager: str) -> None:
    """Install the CUDA toolkit (if absent) + wire it onto PATH. The build discovers the toolkit by
    probing disk, so PATH is a convenience. Blackwell (sm_120) needs >= 12.8. Port of Install-LinuxCuda."""
    cuda_pkg = osenv.resolve_package_name("cuda", manager)
    arch = (osenv.gpu_arch() or {}).get("CudaArch", 120)
    root = osenv.best_cuda_root(arch)
    if root:
        print(f"  CUDA toolkit present: {root} (skipping install)", file=sys.stderr)
    else:
        print(f"  install {cuda_pkg} (CUDA toolkit) ...", file=sys.stderr)
        try:
            osenv.install_package(cuda_pkg)
        except (RuntimeError, KeyError) as e:
            print(f"  {cuda_pkg} failed: {e}", file=sys.stderr)
        root = osenv.best_cuda_root(arch)

    if not root:
        print("  CUDA toolkit >= 12.8 not found after install (looked in /usr/local/cuda*, /opt/cuda, "
              "$CUDA_PATH). Blackwell (sm_120) needs CUDA 12.8+. If your distro's package is older, install "
              "a newer toolkit from https://developer.nvidia.com/cuda-downloads and re-run, or build "
              "CPU-only: ./install_prereqs.sh --cpu && ./setup.sh --cpu", file=sys.stderr)
        return
    host_cxx = osenv.cuda_host_compiler()
    print(f"  CUDA toolkit : {root}", file=sys.stderr)
    if host_cxx:
        print(f"  nvcc host g++: {host_cxx} (the default g++ is too new for nvcc)", file=sys.stderr)
    _set_linux_cuda_path(root, host_cxx)


_ATOMIC_NOTE = """Toolchain layered via rpm-ostree. On an atomic/ostree host (Bazzite / Silverblue /
Kinoite) layered packages apply on the NEXT BOOT — so reboot, then run setup:
    systemctl reboot
    ./setup.sh{cpu}

RECOMMENDED ALTERNATIVE (no reboot, better isolation, simple GPU) — run Bob in a Fedora distrobox:
    distrobox create --name bob --image fedora:latest{nvidia}
    distrobox enter bob
    cd {repo} && ./install_prereqs.sh{cpu} && ./setup.sh{cpu}
Inside the box it's plain Fedora (dnf) — the native build and CUDA passthrough just work, and nothing
touches the immutable host."""


def _layer_atomic(pkgs: list, mgr: str, cpu: bool) -> int:
    """Layer the toolchain on an rpm-ostree host in one transaction. CUDA is intentionally NOT layered on
    the host (it needs NVIDIA's repo + akmods and is fragile on atomic) — the printed note steers GPU users
    to a Fedora distrobox, which is the blessed dev path on Bazzite/Silverblue anyway."""
    print(f"  layering {len(pkgs)} package(s) via rpm-ostree: {' '.join(pkgs)}", file=sys.stderr)
    try:
        osenv.install_packages(pkgs, manager=mgr)
    except (RuntimeError, KeyError) as e:
        raise RuntimeError(
            f"rpm-ostree layering failed: {e}\nOn an atomic host the recommended path is a Fedora "
            "distrobox instead:\n    distrobox create --name bob --image fedora:latest --nvidia && "
            "distrobox enter bob\nthen run ./install_prereqs.sh + ./setup.sh inside it.")
    suffix = " --cpu" if cpu else ""
    nvidia = "" if cpu else " --nvidia"
    print("\n" + _ATOMIC_NOTE.format(cpu=suffix, nvidia=nvidia, repo=REPO), file=sys.stderr)
    return 0


def _prime_sudo() -> None:
    """Ask for the sudo password ONCE, up front, and cache it — so the batched installs below don't
    prompt per package, and a wrong password fails fast (not after hammering every install). No-op when
    already root or sudo is absent (root containers)."""
    if not _sudo():
        return
    print("  sudo is needed — you'll be asked for your password once.", file=sys.stderr)
    if subprocess.run(["sudo", "-v"]).returncode != 0:
        raise RuntimeError("sudo authentication failed. Re-run in a terminal where you can type your "
                           "password (or configure passwordless sudo), then try again.")


def _install_linux(cpu: bool) -> int:
    """Port of Install-LinuxPrereqs: toolchain via PACKAGE_MAP (ONE batched install = one sudo prompt), a
    venv-compatible Python, a build-usable cmake 3.x, optional CUDA + cron + docker. On an atomic/ostree
    host (rpm-ostree) the toolchain LAYERS and applies on the next boot. Fails non-zero if the toolchain
    install fails."""
    mgr = osenv.linux_package_manager()
    if not mgr:
        raise RuntimeError("No supported package manager (apt/dnf/pacman/zypper/rpm-ostree) found. "
                           "Install the toolchain manually — see docs/MANUAL-INSTALL.md.")
    atomic = (mgr == "rpm-ostree")
    print(f"=== Linux prerequisites ({mgr}{' — atomic/ostree host' if atomic else ''}) ===", file=sys.stderr)
    _prime_sudo()

    toolchain = ["git", "curl", "toolchain-cc", "make", "cmake", "ninja", "go", "node", "npm",
                 "python", "python-pip", "python-venv"]
    pkgs = []
    for logical in toolchain:
        name = osenv.resolve_package_name(logical, mgr)
        if name and name not in pkgs:
            pkgs.append(name)  # None => bundled on this manager, skip

    if atomic:
        return _layer_atomic(pkgs, mgr, cpu)

    print(f"  installing {len(pkgs)} package(s): {' '.join(pkgs)}", file=sys.stderr)
    try:
        osenv.install_packages(pkgs, manager=mgr)
    except (RuntimeError, KeyError) as e:
        raise RuntimeError(f"toolchain install failed: {e}\n"
                           f"Fix the error above, then re-run ./install_prereqs.sh{' --cpu' if cpu else ''}.")

    # Guarantee a venv-compatible Python 3.11/3.12 (uv-provisioned if the system one is out of range).
    try:
        py = osenv.bob_python()
        if py:
            print(f"  python (venv) ready: {py}", file=sys.stderr)
        else:
            print("  no venv-compatible Python (3.11/3.12) found and couldn't provision one via uv — "
                  "install Python 3.12 and re-run.", file=sys.stderr)
    except (OSError, subprocess.SubprocessError) as e:
        print(f"  python provisioning failed: {e} (bootstrap will retry)", file=sys.stderr)

    # llama.cpp/whisper.cpp reject cmake >= 4.0; the distro cmake is 4.x on rolling distros. Cache a 3.x.
    try:
        cm3 = osenv.linux_cmake3(REPO)
        print(f"  cmake 3.x ready: {cm3}", file=sys.stderr)
    except (RuntimeError, OSError) as e:
        print(f"  couldn't provision cmake 3.x: {e} (setup will retry)", file=sys.stderr)

    if cpu:
        print("  --cpu: skipping CUDA toolkit (CPU-only tier).", file=sys.stderr)
    elif _have("nvidia-smi"):
        _install_linux_cuda(mgr)
    else:
        print("  No NVIDIA GPU (nvidia-smi absent) — CPU tier. Skipping CUDA.", file=sys.stderr)

    # cron scheduler — Linux parity for Windows Scheduled Tasks (backs `bob agent install`). Optional.
    cron_pkg = osenv.resolve_package_name("cron", mgr)
    if _have("crontab"):
        print("  cron ok (crontab present)", file=sys.stderr)
    else:
        print(f"  install {cron_pkg} (cron scheduler for 'bob agent install') ...", file=sys.stderr)
        try:
            osenv.install_package(cron_pkg)
        except (RuntimeError, KeyError) as e:
            print(f"  {cron_pkg} failed: {e} (optional — needed only for scheduled agents)", file=sys.stderr)
    if _have("crontab") and _have("systemctl"):
        for svc in dict.fromkeys([cron_pkg, "cronie", "crond", "cron"]):
            if subprocess.run([*_sudo(), "systemctl", "enable", "--now", svc],
                              capture_output=True).returncode == 0:
                break

    if _have("docker"):
        print("  docker ok", file=sys.stderr)
    else:
        print("  docker not found (optional — needed only for the compose services). Install docker + "
              "add your user to the docker group.", file=sys.stderr)

    # The toolchain install above raises on failure (batched), so reaching here means it succeeded.
    print(f"\nLinux prerequisites done. Run: ./setup.sh{' --cpu' if cpu else ''}", file=sys.stderr)
    return 0


# --- Windows -------------------------------------------------------------------------------------

_VSWHERE = r"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"


def _install_windows(cpu: bool) -> int:  # pragma: no cover — exercised only on Windows (+ CI acceptance)
    """Port of the install-prereqs.ps1 Windows path: VS2022 C++, Node+uv, Go+Python312 (scoop/winget),
    CUDA (GPU-aware), cmake 3.x, Docker Desktop."""
    if not _have("git"):
        raise RuntimeError("git not found. Install Git from https://git-scm.com, then re-run install_prereqs.bat.")
    have_scoop = _have("scoop")
    print(f"  git ok; scoop {'ok' if have_scoop else 'absent (using winget for go/python)'}", file=sys.stderr)

    # VS2022 with the Desktop C++ workload.
    vs_install = ""
    if Path(_VSWHERE).exists():
        vs_install = subprocess.run([_VSWHERE, "-latest", "-products", "*", "-requires",
                                     "Microsoft.VisualStudio.Workload.NativeDesktop", "-property",
                                     "installationPath"], capture_output=True, text=True).stdout.strip()
    if vs_install:
        print("  VS2022 ok", file=sys.stderr)
    else:
        raise RuntimeError("VS2022 'Desktop development with C++' workload not found — required to compile "
                           "llama.cpp. Install VS2022 (winget install Microsoft.VisualStudio.2022.Community), "
                           "add the 'Desktop development with C++' workload, then re-run install_prereqs.bat.")

    # Node.js + uv.
    if _have("node"):
        print("  node ok", file=sys.stderr)
    else:
        _winget("OpenJS.NodeJS")
    if _have("uvx"):
        print("  uv ok", file=sys.stderr)
    else:
        _winget("astral-sh.uv")

    # Go + Python 3.12.
    if _have("go"):
        print("  go ok", file=sys.stderr)
    elif have_scoop:
        subprocess.run(["scoop", "install", "go"])
    else:
        _winget("GoLang.Go")
    py_ok = _have("python") and osenv.python_at_least("python", "3.12") and \
        (subprocess.run(["python", "--version"], capture_output=True, text=True).stdout.find("3.12") >= 0)
    if py_ok:
        print("  python 3.12 ok", file=sys.stderr)
    elif have_scoop:
        has_py = subprocess.run(["scoop", "prefix", "python312"], capture_output=True).returncode == 0
        if has_py:
            print("  python312 ok", file=sys.stderr)
        else:
            subprocess.run(["scoop", "install", "python312"])
    else:
        _winget("Python.Python.3.12")

    # CUDA (GPU-aware).
    if cpu:
        print("  --cpu: skipping CUDA toolkit (CPU-only tier).", file=sys.stderr)
    else:
        gpu = osenv.gpu_arch()
        arch = gpu["CudaArch"] if gpu else 120
        root = osenv.best_cuda_root(arch)
        if gpu:
            print(f"  Detected GPU: {gpu['Gen']} (sm_{gpu['CudaArch']})", file=sys.stderr)
        if root:
            print(f"  CUDA ok: {root}", file=sys.stderr)
        elif _have("winget"):
            print("  Installing CUDA Toolkit 12.8 (large download)...", file=sys.stderr)
            _winget("Nvidia.CUDA", ["--version", "12.8"])
        else:
            print("  winget not found — install CUDA Toolkit 12.8 manually, then re-run.", file=sys.stderr)

    # cmake 3.x (cmake 4.x excluded by llama.cpp).
    cmake_ok = False
    if _have("cmake"):
        out = subprocess.run(["cmake", "--version"], capture_output=True, text=True).stdout
        import re
        m = re.search(r"(\d+)\.(\d+)\.(\d+)", out)
        if m and (int(m.group(1)), int(m.group(2))) < (4, 0):
            cmake_ok = True
            print(f"  cmake ok ({m.group(0)})", file=sys.stderr)
    if not cmake_ok and Path(_VSWHERE).exists():
        vs_i = subprocess.run([_VSWHERE, "-latest", "-products", "*", "-requires",
                               "Microsoft.VisualStudio.Component.VC.CMake.Project", "-property",
                               "installationPath"], capture_output=True, text=True).stdout.strip()
        bundled = Path(vs_i) / "Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin/cmake.exe"
        if vs_i and bundled.exists():
            cmake_ok = True
            print("  cmake ok (VS bundled 3.31.x)", file=sys.stderr)
    if not cmake_ok:
        print("  Installing cmake 3.31.7 via winget...", file=sys.stderr)
        _winget("Kitware.CMake", ["--version", "3.31.7"])

    # Docker Desktop (optional — only bob up -WithServices needs it; CPU tier skips it).
    docker_exe = Path(r"C:\Program Files\Docker\Docker\Docker Desktop.exe")
    already = cpu or _have("docker") or docker_exe.exists()
    if cpu:
        print("  --cpu: skipping Docker Desktop.", file=sys.stderr)
    elif already:
        print("  Docker Desktop ok", file=sys.stderr)
    else:
        print("  Installing Docker Desktop...", file=sys.stderr)
        _winget("Docker.DockerDesktop")

    if already:
        print("\nAll prerequisites verified. Run setup.bat to build and configure the stack.", file=sys.stderr)
    else:
        print("\nDocker Desktop installed. ACTION REQUIRED: log out of Windows and back in, then run "
              "setup.bat (Docker adds your user to the docker-users group; that takes effect at login).",
              file=sys.stderr)
    return 0


def install_prereqs(cpu: bool = False) -> int:
    """Install all Bob prerequisites (toolchain + a venv-compatible Python). Dispatches Linux vs Windows.
    Returns 0 on success; raises RuntimeError on a fatal toolchain failure. Port of install-prereqs.ps1."""
    if osenv.os_name() == "windows":
        return _install_windows(cpu)
    return _install_linux(cpu)


def main(argv=None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    cpu = "--cpu" in argv or "-Cpu" in argv
    try:
        return install_prereqs(cpu=cpu)
    except RuntimeError as e:
        print(str(e), file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
